---

- name: add vlans configuration for user type vlan
  junos_config:
    lines:
       - set ethernet-switching-options voip interface {{vlan_name}} vlan voip 
       - set protocols vstp vlan {{vlan_name}} interface {{vlan_name}} edge
 


- name: add a port to a specific interface range
  junos_config:
    lines:
      - set interfaces interface-range {{vlan_name}} member {{access_port_add}}
      - set interfaces interface-range {{vlan_name}} unit 0 family ethernet-switching port-mode access
      - set interfaces interface-range {{vlan_name}} unit 0 family ethernet-switching vlan members {{vlan_name}}
 
