---

- name: cretae vlan config using template (cisco)
  template: 
    src: cisco_new_vlan_template.j2
    dest: "./roles/infra_new_vlan/files/{{inventory_hostname}}.txt"

- name: add new vlan to the switch (cisco)
  ios_config:
    src: "./roles/infra_new_vlan/files/{{inventory_hostname}}.txt"
