---
- name: add new vlan to the switch
  junos_config:
    lines:
      - set vlans {{vlan_name}} vlan-id {{vlan_id}}
  
- name: add new vlan layer 3 configuration
  junos_config:
    lines:
      - set interfaces irb unit {{vlan_id}} description {{vlan_name}}
      - set interfaces irb unit {{vlan_id}} family inet address 10.{{site_id}}.{{vlan_id}}.254{{subnet}}
      - set vlans {{vlan_name}} l3-interface irb.{{vlan_id}}
      - set forwarding-options dhcp-relay group clients interface irb.{{vlan_id}}
  when: is_layer3==True

- name: add light cyber port miroring
  junos_config:
    lines:
      - set forwarding-options analyzer lightcyber_Cell input ingress vlan {{vlan_name}}
  when: vlan_type=="users"
  
- name: add other general condfiguration
  junos_config:
    lines:
      - set protocols vstp vlan {{vlan_id}} bridge-priority 4k
