---

- name: cretae vlan config using template
  template: 
    src: junos_new_vlan_template.j2
    dest: "./roles/infra_new_vlan/files/{{inventory_hostname}}.txt"

- name: add new vlan to the switch
  junos_config:
    src: "./roles/infra_new_vlan/files/{{inventory_hostname}}.txt"
    src_format: set