---
- name: include vlan new vlan vars file  
  include_vars: roles/infra_new_vlan/defaults/vlan_details.yml

- name: access & backbone switches new vlan implement
  import_tasks: "junos_new_vlan_add.yml"