---
- name: include vlan new vlan vars file  
  include_vars: roles/infra_new_vlan/defaults/vlan_details.yml

- name: valadition that check if the new vlan exist (junos)
  import_tasks: "junos_validation_check.yml"
  when: hostvars[inventory_hostname].group == "junos"

- name: valadition that check if the new vlan exist (junos test machines)
  import_tasks: "junos_validation_check.yml"
  when: hostvars[inventory_hostname].group == "test_junos"

- name: valadition that check if the new vlan exist (cisco)
  import_tasks: "cisco_validation_check.yml"
  when: hostvars[inventory_hostname].group == "cisco"

- name: access & backbone switches new vlan implement (junos)
  import_tasks: "junos_new_vlan_add.yml"
  when: hostvars[inventory_hostname].group == "junos"  

- name: access & backbone switches new vlan implement (junos test machines)
  import_tasks: "junos_new_vlan_add.yml"
  when: hostvars[inventory_hostname].group == "test_junos"  

- name: access & backbone switches new vlan implement (cisco)
  import_tasks: "cisco_new_vlan_add.yml"
  when: hostvars[inventory_hostname].group== "cisco"