---
# tasks file for infra_new_vlan
# - name: "distribution switches new vlan implement "
#   import_tasks: "dist_vlan_add.yml"

- name: access switches new vlan implement
  import_tasks: "access_vlan_add.yml"
