---
- name: add new vlan to the switch
  junos_config:
    lines:
      - set vlans {{vlan_name}} vlan-id {{vlan_id}}
  
- name: add new vlan layer 3 configuration (ex3400/qfx)
  junos_config:
    lines:
      - set interfaces irb unit {{vlan_id}} description {{vlan_name}}
      - set interfaces irb unit {{vlan_id}} family inet address 10.{{site_id}}.{{vlan_id}}.254{{subnet}}
      - set vlans {{vlan_name}} l3-interface irb.{{vlan_id}}
      - set forwarding-options dhcp-relay group clients interface irb.{{vlan_id}}
  when: 
   - is_layer3==True
   - (hostvars[inventory_hostname].model=="qfx") or (hostvars[inventory_hostname].model=="ex3400") or (hostvars[inventory_hostname].model=="ex4600")


- name: add new vlan layer 3 configuration (ex3300)
  junos_config:
    lines:
      - set interfaces vlan unit {{vlan_id}} description {{vlan_name}}
      - set interfaces vlan unit {{vlan_id}} family inet address 10.{{site_id}}.{{vlan_id}}.254{{subnet}}
      - set vlans {{vlan_name}} l3-interface vlan.{{vlan_id}}
      - set forwarding-options helpers bootp interface vlan.{{vlan_id}} server {{dhcp_server}}
  when: 
   - is_layer3==True
   - hostvars[inventory_hostname].model=="ex3300"

- name: add light cyber port miroring (pt-qfx)
  junos_config:
    lines:
      - set forwarding-options analyzer lightcyber_Cell input ingress vlan {{vlan_name}}
  when: 
    - vlan_type=="users"
    - location=="PT"
    - hostvars[inventory_hostname].model=="qfx"
  
- name: add other general condfiguration (qfx)
  junos_config:
    lines:
      - set protocols vstp vlan {{vlan_id}} bridge-priority 4k
  when: hostvars[inventory_hostname].model=="qfx"
