---

- name: test if vlan exist
  junos_command:
   commands: show vlan {{vlan_id}}
   display: xml   
  register: result

- set_fact:
    is_vlan_exists: "{{result['output'][0]['rpc-reply']['error']['message'] | default('true') }}"

- fail:
    msg: "the vlan you are trying to configure is already exist in one of the switches "
  when: is_vlan_exists==true